Fix boost builds for x86-64 Android
Boost always assumes the legacy x87 80-bit format for floating point
numbers under x86-64. Android uses the IEEE 754 128-bit format under x86-64
as well, though. Google probably did this to ensure precision consistency
across the entire Android ecosystem.

Hence the compilation of Boost fails with without the added patch:

```
./boost/math/special_functions/detail/fp_traits.hpp:314:15: error: static assertion failed due to requirement '113 == 64': Oops, assumption that long double is an 80-bit quantity is incorrect!!
  314 | static_assert(LDBL_MANT_DIG == 64, "Oops, assumption that long double is an 80-bit quantity is incorrect!!");
      |               ^~~~~~~~~~~~~~~~~~~
/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/21/include/float.h:114:23: note: expanded from macro 'LDBL_MANT_DIG'
  114 | #define LDBL_MANT_DIG __LDBL_MANT_DIG__
      |                       ^
<built-in>:243:27: note: expanded from macro '__LDBL_MANT_DIG__'
  243 | #define __LDBL_MANT_DIG__ 113
```