Add workaround to compile static-compat-gcc after host glibc update
Ensure that ada host tools are built/linked with host g++ and thus linked
against the host glibc. Attempting to link against the target glibc leads
otherwise to linker errors like (since the host glibc has been updated to
2.38):

```
/usr/bin/ld: ../../libcommon.a(diagnostic.o): in function `get_terminal_width()':
/usr/include/stdlib.h:483:(.text+0x790): undefined reference to `__isoc23_strtol'
```

Not sure why GCC's build script is using the target "xg++" tool here. Maybe
a misconfiguration on my side or an upstream bug.